export const PRICING_COPY = {
  fr: {
    title: "Investissez dans votre Avenir",
    text: "Des offres flexibles pour candidats, cabinets de recrutement et écoles. Payez uniquement ce que vous utilisez.",
    currentBalance: "Votre solde actuel",
    credits: "jetons",
    segmentCandidate: "Candidat / Étudiant",
    segmentAgency: "Cabinet de recrutement / Conseil",
    segmentSchool: "École / Établissement",
    billingMonthly: "Mensuel",
    billingAnnual: "Annuel",
    billingSave: "jusqu'à 2 mois offerts",
    free: "Gratuit",
    perMonth: "/ mois",
    perYear: "/ an",
    creditsIncluded: "jetons inclus",
    seatsIncluded: "sièges inclus",
    studentSeatsLabel: "Nombre d'étudiants",
    studentSeatsTotal: "Total à payer :",
    studentSeatsMaxHint: "Ce palier est limité à {max} étudiants. Au-delà, passez au palier supérieur.",
    contactSales: "Nous contacter",
    activate: "Activer",
    currentPlan: "Plan actuel",
    licenseCodeTitle: "Vous avez reçu un code de licence ?",
    licenseCodePlaceholder: "Ex : LIC-XXXX-XXXX",
    licenseCodeSubmit: "Activer",
    licenseCodeHint: "Votre établissement ou votre cabinet vous a transmis un code ? Activez-le ici pour débloquer votre offre.",
    licenseCodeCurrent: "Vous êtes déjà rattaché à la licence {code}. Activer un nouveau code vous en fera changer (après confirmation).",
    tabPlans: "Tarifs",
    tabHistory: "Historique paiement",
    historyEmpty: "Aucun paiement pour le moment. Une fois un plan activé, il apparaîtra ici.",
    historyLoading: "Chargement de l'historique...",
    historyError: "Impossible de charger l'historique de paiement.",
    historyColDate: "Date",
    historyColPlan: "Plan",
    historyColAmount: "Montant",
    historyColSource: "Moyen",
    historyColStatus: "Statut",
    historySourceStripe: "Carte bancaire (Stripe)",
    historySourceInstant: "Activation instantanée",
    historySourceLicenseRedeem: "Code de licence",
    historyStatusPaid: "Payé",
    historyStatusFree: "Sans frais",
    historyStatusRefunded: "Remboursé",
    historyCycleMonthly: "Mensuel",
    historyCycleAnnual: "Annuel",
    downgradeBlockedTitle: "Impossible de revenir à Essentiel",
    downgradeBlockedText: "Vous avez déjà un plan payant actif. Repasser à Essentiel effacerait vos jetons restants — ce n'est pas proposé ici. Contactez le support si vous souhaitez vraiment annuler votre plan.",
    downgradeBlockedOk: "Compris",
    upgradeConfirmTitle: "Passer à {plan} ?",
    upgradeConfirmText: "Vos {credits} jetons restants seront conservés et s'ajouteront aux {planCredits} jetons de {plan}.",
    upgradeConfirmOk: "Confirmer",
    upgradeConfirmCancel: "Annuler",
    historyFilterStatusLabel: "Statut",
    historyFilterStatusAll: "Tous",
    historyFilterPlanLabel: "Plan",
    historyFilterPlanAll: "Tous les plans",
    historyPagePrev: "Précédent",
    historyPageNext: "Suivant",
    historyPageInfo: "Page {page} sur {totalPages}",
    historyNoResults: "Aucun paiement ne correspond à ces filtres.",
    balanceEmptyTitle: "Solde épuisé",
    balanceEmptyText: "Vous n'avez plus de jetons. Choisissez un plan ci-dessous pour continuer à utiliser les modules IA.",
    balanceLowTitle: "Solde bientôt épuisé",
    balanceLowText: "Il vous reste peu de jetons. Pensez à recharger pour ne pas être bloqué en pleine action.",
    balanceUnlimitedTitle: "Accès illimité actif",
    balanceUnlimitedText: "Votre compte est couvert par une licence école ou cabinet : tous les modules sont disponibles sans limite de jetons, l'achat d'un plan individuel n'est pas nécessaire.",
    alreadyUnlimited: "Déjà inclus"
  },
  en: {
    title: "Invest in your Future",
    text: "Flexible offers for candidates, recruitment firms and schools. Pay only for what you use.",
    currentBalance: "Your current balance",
    credits: "tokens",
    segmentCandidate: "Candidate / Student",
    segmentAgency: "Recruitment firm / Consulting",
    segmentSchool: "School / Institution",
    billingMonthly: "Monthly",
    billingAnnual: "Annual",
    billingSave: "up to 2 months free",
    free: "Free",
    perMonth: "/ month",
    perYear: "/ year",
    creditsIncluded: "tokens included",
    seatsIncluded: "seats included",
    studentSeatsLabel: "Number of students",
    studentSeatsTotal: "Total to pay:",
    studentSeatsMaxHint: "This tier is capped at {max} students. Move to the next tier beyond that.",
    contactSales: "Contact us",
    activate: "Activate",
    currentPlan: "Current plan",
    licenseCodeTitle: "Received a license code?",
    licenseCodePlaceholder: "E.g. LIC-XXXX-XXXX",
    licenseCodeSubmit: "Activate",
    licenseCodeHint: "Your school or firm gave you a code? Activate it here to unlock your offer.",
    licenseCodeCurrent: "You're already using license {code}. Activating a new code will switch you over (after confirmation).",
    tabPlans: "Pricing",
    tabHistory: "Payment history",
    historyEmpty: "No payment yet. Once you activate a plan, it will show up here.",
    historyLoading: "Loading history...",
    historyError: "Could not load payment history.",
    historyColDate: "Date",
    historyColPlan: "Plan",
    historyColAmount: "Amount",
    historyColSource: "Method",
    historyColStatus: "Status",
    historySourceStripe: "Card (Stripe)",
    historySourceInstant: "Instant activation",
    historySourceLicenseRedeem: "License code",
    historyStatusPaid: "Paid",
    historyStatusFree: "No charge",
    historyStatusRefunded: "Refunded",
    historyCycleMonthly: "Monthly",
    historyCycleAnnual: "Annual",
    downgradeBlockedTitle: "Can't switch back to Essentiel",
    downgradeBlockedText: "You already have an active paid plan. Switching back to Essentiel would erase your remaining tokens — that's not offered here. Contact support if you really want to cancel your plan.",
    downgradeBlockedOk: "Got it",
    upgradeConfirmTitle: "Switch to {plan}?",
    upgradeConfirmText: "Your {credits} remaining tokens will be kept and added to {plan}'s {planCredits} tokens.",
    upgradeConfirmOk: "Confirm",
    upgradeConfirmCancel: "Cancel",
    historyFilterStatusLabel: "Status",
    historyFilterStatusAll: "All",
    historyFilterPlanLabel: "Plan",
    historyFilterPlanAll: "All plans",
    historyPagePrev: "Previous",
    historyPageNext: "Next",
    historyPageInfo: "Page {page} of {totalPages}",
    historyNoResults: "No payment matches these filters.",
    balanceEmptyTitle: "Balance empty",
    balanceEmptyText: "You're out of tokens. Pick a plan below to keep using the AI modules.",
    balanceLowTitle: "Balance running low",
    balanceLowText: "You don't have many tokens left. Top up so you don't get blocked mid-action.",
    balanceUnlimitedTitle: "Unlimited access active",
    balanceUnlimitedText: "Your account is covered by a school or firm license: every module is available with no token limit, buying an individual plan isn't needed.",
    alreadyUnlimited: "Already included"
  }
};
