export const SKILLS_TEST_COPY = {
  fr: {
    title: "Quiz sur l'offre",
    subtitle: "Un questionnaire généré à partir de l'offre analysée : 8 questions à choix multiples, notées automatiquement.",
    empty: "Importez un CV et analysez une offre pour débloquer ce module.",
    startDescription: "8 questions à choix multiples, pour environ 5 minutes. Vous obtenez une note finale sur 10 à la fin.",
    generate: "Générer mon test",
    generating: "Génération du test en cours...",
    error: "Une erreur est survenue.",
    questionProgress: "Question {current} sur {total}",
    qcmChoicePlaceholder: "Choisissez une réponse",
    nextQuestion: "Question suivante",
    finishAndGrade: "Terminer et noter",
    grading: "Notation en cours...",
    resultTitle: "Résultat de votre test",
    resultScoreOn: "sur 10",
    resultDetailTitle: "Détail par question",
    retakeTest: "Nouveau test",
    newTest: "Nouveau test",
    history: "Tests",
    noHistory: "Aucun test pour l'instant.",
    deleteTest: "Supprimer",
    deleteConfirm: "Supprimer ce test ?",
    cancel: "Annuler",
    untitled: "Test sans titre",
    statusPending: "En attente"
  },
  en: {
    title: "Quiz on the offer",
    subtitle: "A questionnaire generated from the analyzed job offer: 8 multiple-choice questions, graded automatically.",
    empty: "Import a CV and analyze a job offer to unlock this module.",
    startDescription: "8 multiple-choice questions, about 5 minutes. You get a final score out of 10 at the end.",
    generate: "Generate my test",
    generating: "Generating your test...",
    error: "Something went wrong.",
    questionProgress: "Question {current} of {total}",
    qcmChoicePlaceholder: "Choose an answer",
    nextQuestion: "Next question",
    finishAndGrade: "Finish and grade",
    grading: "Grading in progress...",
    resultTitle: "Your test result",
    resultScoreOn: "out of 10",
    resultDetailTitle: "Detail by question",
    retakeTest: "New test",
    newTest: "New test",
    history: "Tests",
    noHistory: "No test yet.",
    deleteTest: "Delete",
    deleteConfirm: "Delete this test?",
    cancel: "Cancel",
    untitled: "Untitled test",
    statusPending: "Pending"
  }
};
