export const SKILLS_TEST_COPY = {
  fr: {
    title: "Test de compétences",
    subtitle: "Un questionnaire généré à partir de l'offre analysée : 5 QCM et 3 questions ouvertes, noté automatiquement.",
    empty: "Importez un CV et analysez une offre pour débloquer ce module.",
    startDescription: "8 questions au total (5 QCM notées automatiquement, 3 questions ouvertes notées par IA), pour environ 10 minutes. Vous obtenez une note finale sur 100 à la fin.",
    generate: "Générer mon test (1 jeton)",
    generateUnlimited: "Générer mon test",
    generating: "Génération du test en cours...",
    noTokens: "Il vous manque des jetons pour générer un test. Passez à un plan supérieur.",
    noTokensCta: "Passer à un plan supérieur",
    error: "Une erreur est survenue.",
    questionProgress: "Question {current} sur {total}",
    qcmChoicePlaceholder: "Choisissez une réponse",
    openAnswerPlaceholder: "Rédigez votre réponse ici...",
    nextQuestion: "Question suivante",
    finishAndGrade: "Terminer et noter",
    grading: "Notation en cours...",
    resultTitle: "Résultat de votre test",
    resultScoreOn: "sur 100",
    resultDetailTitle: "Détail par question",
    retakeTest: "Nouveau test (1 jeton)",
    retakeTestUnlimited: "Nouveau test",
    yourAnswer: "Votre réponse :",
    qcmType: "QCM",
    openType: "Question ouverte",
    newTest: "Nouveau test",
    history: "Tests",
    noHistory: "Aucun test pour l'instant.",
    deleteTest: "Supprimer",
    deleteConfirm: "Supprimer ce test ?",
    cancel: "Annuler",
    untitled: "Test sans titre",
    statusPending: "En attente"
  },
  en: {
    title: "Skills test",
    subtitle: "A questionnaire generated from the analyzed job offer: 5 multiple-choice questions and 3 open questions, graded automatically.",
    empty: "Import a CV and analyze a job offer to unlock this module.",
    startDescription: "8 questions in total (5 multiple-choice, auto-graded, and 3 open questions graded by AI), about 10 minutes. You get a final score out of 100 at the end.",
    generate: "Generate my test (1 token)",
    generateUnlimited: "Generate my test",
    generating: "Generating your test...",
    noTokens: "You don't have enough tokens to generate a test. Upgrade your plan.",
    noTokensCta: "Upgrade your plan",
    error: "Something went wrong.",
    questionProgress: "Question {current} of {total}",
    qcmChoicePlaceholder: "Choose an answer",
    openAnswerPlaceholder: "Write your answer here...",
    nextQuestion: "Next question",
    finishAndGrade: "Finish and grade",
    grading: "Grading in progress...",
    resultTitle: "Your test result",
    resultScoreOn: "out of 100",
    resultDetailTitle: "Detail by question",
    retakeTest: "New test (1 token)",
    retakeTestUnlimited: "New test",
    yourAnswer: "Your answer:",
    qcmType: "Multiple choice",
    openType: "Open question",
    newTest: "New test",
    history: "Tests",
    noHistory: "No test yet.",
    deleteTest: "Delete",
    deleteConfirm: "Delete this test?",
    cancel: "Cancel",
    untitled: "Untitled test",
    statusPending: "Pending"
  }
};
