export const HOME_COPY = {
  fr: {
    userFallback: "Utilisateur",
    greetingMorning: "Bonjour",
    greetingEvening: "Bonsoir",
    eyebrow: "Assistant carrière propulsé par l'IA",
    titleA: "Décrochez le poste",
    titleB: "qui vous correspond,",
    titleAccent: "guidé par la data.",
    intro: "Importez votre CV, analysez une offre, puis préparez lettre, entretien et négociation : tout votre parcours de candidature au même endroit.",
    ctaImport: "Importer mon CV",
    ctaAnalyse: "Analyser une offre",
    ctaResults: "Voir ma dernière analyse",
    seeTarifs: "Voir les tarifs",
    schoolMember: "Compte activé via",
    statScore: "Dernier score",
    statScoreNone: "Aucune analyse",
    statCv: "CV importés",
    statApplications: "Candidatures",
    statProfile: "Profil complété",
    statTokens: "Jetons",
    unlimited: "Illimité",
    journeyTitle: "Votre parcours",
    journeyText: "Suivez les étapes : chacune s'appuie sur la précédente.",
    stepDone: "Fait",
    stepTodo: "À faire",
    steps: [
      { key: "cv", title: "Importer votre CV", text: "L'IA extrait votre profil en quelques secondes.", page: "import" },
      { key: "match", title: "Analyser une offre", text: "Score de compatibilité et compétences à renforcer.", page: "import" },
      { key: "track", title: "Suivre vos candidatures", text: "Relances, entretiens et offres au même endroit.", page: "candidatures" },
      { key: "train", title: "Vous entraîner", text: "Entretien et négociation face à un recruteur IA.", page: "entretiens" }
    ],
    lastAnalysisTitle: "Dernière analyse",
    lastAnalysisOpen: "Ouvrir l'analyse",
    modulesTitle: "Vos outils",
    modules: [
      { page: "lettre", icon: "mail", title: "Lettre IA", text: "Une lettre personnalisée pour chaque offre." },
      { page: "entretiens", icon: "chat", title: "Entretiens", text: "Simulation en chat ou en vocal, avec bilan." },
      { page: "negociation", icon: "scale", title: "Négociation", text: "Défendez votre salaire face à un recruteur IA." },
      { page: "email-finder", icon: "network", title: "Email Scout", text: "Trouvez l'email du recruteur." }
    ],
    moduleGo: "Ouvrir"
  },
  en: {
    userFallback: "User",
    greetingMorning: "Good morning",
    greetingEvening: "Good evening",
    eyebrow: "AI-powered career assistant",
    titleA: "Land the job",
    titleB: "that fits you,",
    titleAccent: "guided by data.",
    intro: "Import your CV, analyze a job offer, then prepare your cover letter, interview and negotiation: your whole application journey in one place.",
    ctaImport: "Import my CV",
    ctaAnalyse: "Analyze a job offer",
    ctaResults: "See my latest analysis",
    seeTarifs: "See pricing",
    schoolMember: "Account activated via",
    statScore: "Latest score",
    statScoreNone: "No analysis yet",
    statCv: "CVs imported",
    statApplications: "Applications",
    statProfile: "Profile completed",
    statTokens: "Tokens",
    unlimited: "Unlimited",
    journeyTitle: "Your journey",
    journeyText: "Follow the steps: each one builds on the previous.",
    stepDone: "Done",
    stepTodo: "To do",
    steps: [
      { key: "cv", title: "Import your CV", text: "The AI extracts your profile in seconds.", page: "import" },
      { key: "match", title: "Analyze a job offer", text: "Compatibility score and skills to strengthen.", page: "import" },
      { key: "track", title: "Track your applications", text: "Follow-ups, interviews and offers in one place.", page: "candidatures" },
      { key: "train", title: "Practise", text: "Interview and negotiation with an AI recruiter.", page: "entretiens" }
    ],
    lastAnalysisTitle: "Latest analysis",
    lastAnalysisOpen: "Open the analysis",
    modulesTitle: "Your tools",
    modules: [
      { page: "lettre", icon: "mail", title: "AI Letter", text: "A personalised letter for every job." },
      { page: "entretiens", icon: "chat", title: "Interviews", text: "Chat or voice simulation, with a report." },
      { page: "negociation", icon: "scale", title: "Negotiation", text: "Defend your salary against an AI recruiter." },
      { page: "email-finder", icon: "network", title: "Email Scout", text: "Find the recruiter's email." }
    ],
    moduleGo: "Open"
  }
};
