// Textes (FR/EN) du module Suivi de candidatures. Aussi importé depuis
// App.jsx (étape "Analyse" de l'import CV) pour le bouton "Ajouter au suivi
// de candidatures" — ce module a donc deux points d'entrée légitimes.
export const APPLICATIONS_COPY = {
  fr: {
    title: "Suivi de candidatures",
    heroEyebrow: "Suivi · Candidatures",
    kpiTotal: "candidatures",
    kpiInProgress: "en cours",
    kpiInterviews: "en entretien",
    kpiResponseRate: "taux de réponse",
    kpiResponseRateHint: "Part des candidatures envoyées ayant obtenu une réponse (entretien, offre ou refus).",
    remindersOverdue: "{count} relance(s) en retard",
    remindersUpcoming: "{count} relance(s) prévue(s) dans les 7 prochains jours",
    followUpOn: "Relance le",
    followUpLate: "Relance en retard",
    dropHint: "Glissez une candidature ici",
    emptyFirst: "Ajoutez votre première candidature pour commencer le suivi.",
    text: "Gardez une vue d'ensemble sur vos candidatures, de la découverte de l'offre à la réponse finale.",
    addButton: "Ajouter une candidature",
    empty: "Aucune candidature ici.",
    loading: "Chargement…",
    columnToApply: "À postuler",
    columnApplied: "Postulé",
    columnInterview: "Entretien",
    columnOffer: "Offre",
    columnRejected: "Refusé",
    formNewTitle: "Nouvelle candidature",
    formEditTitle: "Modifier la candidature",
    formSubtitle: "Les champs marqués d'un astérisque : au moins l'un des deux est requis.",
    formTitleLabel: "Intitulé du poste",
    formCompanyLabel: "Entreprise",
    formTitleHint: "Renseignez au moins l'intitulé du poste ou l'entreprise.",
    formLocationLabel: "Lieu",
    formStatusLabel: "Statut",
    formUrlLabel: "Lien de l'offre",
    formAppliedLabel: "Date de candidature",
    formNextActionLabel: "Prochaine relance",
    formNotesLabel: "Notes",
    formSaveAnyway: "Ajouter quand même",
    formErrorTitleOrCompany: "Indiquez au moins l'intitulé du poste ou l'entreprise.",
    formErrorTooLong: "{max} caractères maximum.",
    formErrorUrl: "Lien invalide : saisissez une adresse web (ex. https://site.fr/offre).",
    formErrorAppliedFuture: "La date de candidature ne peut pas être dans le futur.",
    formErrorNextBeforeApplied: "La relance doit être postérieure à la date de candidature.",
    formErrorCv: "Ce CV n'existe plus : choisissez-en un autre.",
    formErrorGeneric: "Enregistrement impossible. Réessayez.",
    formDuplicateWarning: "Une candidature identique (même poste, même entreprise) existe déjà dans votre suivi. Cliquez à nouveau pour l'ajouter quand même.",
    formTitlePlaceholder: "Ex. Chargé de communication",
    formCompanyPlaceholder: "Ex. Decathlon",
    formLocationPlaceholder: "Ex. Lyon, télétravail partiel",
    formUrlPlaceholder: "Lien de l'offre (optionnel)",
    formCvLabel: "CV utilisé",
    formCvNone: "Aucun CV lié",
    formCancel: "Annuler",
    formSave: "Enregistrer",
    formSaving: "Enregistrement…",
    formError: "Indique au moins un poste ou une entreprise.",
    deleteConfirmTitle: "Supprimer cette candidature ?",
    delete: "Supprimer",
    edit: "Modifier",
    matchScoreLabel: "Score",
    appliedAtLabel: "Postulé le",
    addedOnLabel: "Ajouté le",
    nextActionLabel: "Prochaine relance",
    notesPlaceholder: "Contact, points à préparer, retours reçus…",
    addToTrackerBtn: "Ajouter au suivi de candidatures",
    removeFromTrackerBtn: "Retirer du suivi",
    addedToTracker: "Ajouté au suivi de candidatures.",
    removedFromTracker: "Retiré du suivi de candidatures.",
    cardOpenOffer: "Voir l'offre",
    statusMessageToApply: "{title} chez {company} déplacée vers À postuler.",
    statusMessageApplied: "Bravo, vous avez postulé pour {title} chez {company} ! Encore un pas de plus 💪",
    statusMessageInterview: "Un entretien pour {title} chez {company} ? Félicitations, préparez-vous bien 🎯",
    statusMessageOffer: "Une offre pour {title} chez {company} ! Bravo, quelle belle nouvelle 🎉",
    statusMessageRejected: "{title} chez {company} n'a pas abouti cette fois. Ce n'est qu'une étape, la bonne offre arrive."
  },
  en: {
    title: "Application tracker",
    heroEyebrow: "Tracking · Applications",
    kpiTotal: "applications",
    kpiInProgress: "in progress",
    kpiInterviews: "interviewing",
    kpiResponseRate: "response rate",
    kpiResponseRateHint: "Share of sent applications that got an answer (interview, offer or rejection).",
    remindersOverdue: "{count} overdue follow-up(s)",
    remindersUpcoming: "{count} follow-up(s) due in the next 7 days",
    followUpOn: "Follow up on",
    followUpLate: "Follow-up overdue",
    dropHint: "Drag an application here",
    emptyFirst: "Add your first application to start tracking.",
    text: "Keep track of your applications, from finding the job to the final answer.",
    addButton: "Add an application",
    empty: "No applications here.",
    loading: "Loading…",
    columnToApply: "To apply",
    columnApplied: "Applied",
    columnInterview: "Interview",
    columnOffer: "Offer",
    columnRejected: "Rejected",
    formNewTitle: "New application",
    formEditTitle: "Edit application",
    formSubtitle: "Fields marked with an asterisk: at least one of the two is required.",
    formTitleLabel: "Job title",
    formCompanyLabel: "Company",
    formTitleHint: "Enter at least the job title or the company.",
    formLocationLabel: "Location",
    formStatusLabel: "Status",
    formUrlLabel: "Job posting link",
    formAppliedLabel: "Application date",
    formNextActionLabel: "Next follow-up",
    formNotesLabel: "Notes",
    formSaveAnyway: "Add anyway",
    formErrorTitleOrCompany: "Enter at least the job title or the company.",
    formErrorTooLong: "{max} characters maximum.",
    formErrorUrl: "Invalid link: enter a web address (e.g. https://site.com/job).",
    formErrorAppliedFuture: "The application date cannot be in the future.",
    formErrorNextBeforeApplied: "The follow-up must come after the application date.",
    formErrorCv: "This CV no longer exists: pick another one.",
    formErrorGeneric: "Could not save. Please try again.",
    formDuplicateWarning: "An identical application (same job, same company) is already in your tracker. Click again to add it anyway.",
    formTitlePlaceholder: "E.g. Communications officer",
    formCompanyPlaceholder: "E.g. Decathlon",
    formLocationPlaceholder: "E.g. Lyon, hybrid",
    formUrlPlaceholder: "Job posting link (optional)",
    formCvLabel: "CV used",
    formCvNone: "No linked CV",
    formCancel: "Cancel",
    formSave: "Save",
    formSaving: "Saving…",
    formError: "Enter at least a job title or a company.",
    deleteConfirmTitle: "Delete this application?",
    delete: "Delete",
    edit: "Edit",
    matchScoreLabel: "Score",
    appliedAtLabel: "Applied on",
    addedOnLabel: "Added on",
    nextActionLabel: "Next follow-up",
    notesPlaceholder: "Contact, things to prepare, feedback received…",
    addToTrackerBtn: "Add to application tracker",
    removeFromTrackerBtn: "Remove from tracker",
    addedToTracker: "Added to your application tracker.",
    removedFromTracker: "Removed from your application tracker.",
    cardOpenOffer: "View the job posting",
    statusMessageToApply: "{title} at {company} moved back to To apply.",
    statusMessageApplied: "Nice, you applied to {title} at {company}! One step closer 💪",
    statusMessageInterview: "An interview for {title} at {company}? Congrats, go prepare well 🎯",
    statusMessageOffer: "An offer for {title} at {company}! Congratulations, what great news 🎉",
    statusMessageRejected: "{title} at {company} didn't work out this time. It's just one step, the right offer is coming."
  }
};
