// Textes (FR/EN) du module Suivi de candidatures. Aussi importé depuis
// App.jsx (étape "Analyse" de l'import CV) pour le bouton "Ajouter au suivi
// de candidatures" — ce module a donc deux points d'entrée légitimes.
export const APPLICATIONS_COPY = {
  fr: {
    title: "Suivi de candidatures",
    text: "Gardez une vue d'ensemble sur vos candidatures, de la découverte de l'offre à la réponse finale.",
    addButton: "Ajouter une candidature",
    empty: "Aucune candidature ici.",
    loading: "Chargement…",
    columnToApply: "À postuler",
    columnApplied: "Postulé",
    columnInterview: "Entretien",
    columnOffer: "Offre",
    columnRejected: "Refusé",
    formTitlePlaceholder: "Intitulé du poste",
    formCompanyPlaceholder: "Entreprise",
    formLocationPlaceholder: "Lieu (optionnel)",
    formUrlPlaceholder: "Lien de l'offre (optionnel)",
    formCvLabel: "CV utilisé (optionnel)",
    formCvNone: "Aucun CV lié",
    formCancel: "Annuler",
    formSave: "Enregistrer",
    formSaving: "Enregistrement…",
    formError: "Indique au moins un poste ou une entreprise.",
    deleteConfirmTitle: "Supprimer cette candidature ?",
    delete: "Supprimer",
    edit: "Modifier",
    matchScoreLabel: "Score",
    appliedAtLabel: "Postulé le",
    addedOnLabel: "Ajouté le",
    nextActionLabel: "Prochaine relance",
    notesPlaceholder: "Notes (optionnel)",
    addToTrackerBtn: "Ajouter au suivi de candidatures",
    removeFromTrackerBtn: "Retirer du suivi",
    addedToTracker: "Ajouté au suivi de candidatures.",
    removedFromTracker: "Retiré du suivi de candidatures.",
    cardOpenOffer: "Voir l'offre",
    statusMessageToApply: "{title} chez {company} déplacée vers À postuler.",
    statusMessageApplied: "Bravo, vous avez postulé pour {title} chez {company} ! Encore un pas de plus 💪",
    statusMessageInterview: "Un entretien pour {title} chez {company} ? Félicitations, préparez-vous bien 🎯",
    statusMessageOffer: "Une offre pour {title} chez {company} ! Bravo, quelle belle nouvelle 🎉",
    statusMessageRejected: "{title} chez {company} n'a pas abouti cette fois. Ce n'est qu'une étape — la bonne offre arrive."
  },
  en: {
    title: "Application tracker",
    text: "Keep track of your applications, from finding the job to the final answer.",
    addButton: "Add an application",
    empty: "No applications here.",
    loading: "Loading…",
    columnToApply: "To apply",
    columnApplied: "Applied",
    columnInterview: "Interview",
    columnOffer: "Offer",
    columnRejected: "Rejected",
    formTitlePlaceholder: "Job title",
    formCompanyPlaceholder: "Company",
    formLocationPlaceholder: "Location (optional)",
    formUrlPlaceholder: "Job posting link (optional)",
    formCvLabel: "CV used (optional)",
    formCvNone: "No linked CV",
    formCancel: "Cancel",
    formSave: "Save",
    formSaving: "Saving…",
    formError: "Enter at least a job title or a company.",
    deleteConfirmTitle: "Delete this application?",
    delete: "Delete",
    edit: "Edit",
    matchScoreLabel: "Score",
    appliedAtLabel: "Applied on",
    addedOnLabel: "Added on",
    nextActionLabel: "Next follow-up",
    notesPlaceholder: "Notes (optional)",
    addToTrackerBtn: "Add to application tracker",
    removeFromTrackerBtn: "Remove from tracker",
    addedToTracker: "Added to your application tracker.",
    removedFromTracker: "Removed from your application tracker.",
    cardOpenOffer: "View the job posting",
    statusMessageToApply: "{title} at {company} moved back to To apply.",
    statusMessageApplied: "Nice, you applied to {title} at {company}! One step closer 💪",
    statusMessageInterview: "An interview for {title} at {company}? Congrats, go prepare well 🎯",
    statusMessageOffer: "An offer for {title} at {company}! Congratulations, what great news 🎉",
    statusMessageRejected: "{title} at {company} didn't work out this time. It's just one step — the right offer is coming."
  }
};
