export const PROFILE_COPY = {
  fr: {
    addHeadline: "Ajoutez un titre professionnel cible.",
    completeness: "Complétude du profil",
    plan: "Plan",
    professional: "Profil professionnel",
    headline: "Titre / headline",
    targetRole: "Rôle cible",
    sector: "Secteur visé",
    location: "Localisation",
    experience: "Expérience (ans)",
    education: "Niveau d'études",
    skills: "Compétences (séparées par des virgules)",
    languages: "Langues (séparées par des virgules)",
    saveProfile: "Sauvegarder le profil",
    accountSettings: "Paramètres compte (SaaS)",
    accountType: "Type de compte",
    phone: "Téléphone",
    city: "Ville",
    country: "Pays",
    saveAccount: "Sauvegarder le compte",
    premiumTitle: "Offre premium dynamique",
    premiumText: "L'activation premium se base sur le score de profil, l'historique de matching et la complétude d'onboarding.",
    level: "Niveau",
    accessOpen: "Accès ouvert",
    accessRestricted: "Accès restreint",
    accessSource: "Source d'accès",
    renewal: "Renouvellement",
    activatePremium: "Activer l'offre premium",
    upload: "Changer photo",
    uploading: "Upload..."
  },
  en: {
    addHeadline: "Add a target professional headline.",
    completeness: "Profile completeness",
    plan: "Plan",
    professional: "Professional profile",
    headline: "Title / headline",
    targetRole: "Target role",
    sector: "Target sector",
    location: "Location",
    experience: "Experience (years)",
    education: "Education level",
    skills: "Skills (comma separated)",
    languages: "Languages (comma separated)",
    saveProfile: "Save profile",
    accountSettings: "Account settings (SaaS)",
    accountType: "Account type",
    phone: "Phone",
    city: "City",
    country: "Country",
    saveAccount: "Save account",
    premiumTitle: "Dynamic premium offer",
    premiumText: "Premium activation is based on your profile score, match history, and onboarding completeness.",
    level: "Level",
    accessOpen: "Access open",
    accessRestricted: "Access restricted",
    accessSource: "Access source",
    renewal: "Renewal",
    activatePremium: "Activate premium offer",
    upload: "Change photo",
    uploading: "Uploading..."
  }
};
