// Textes (FR/EN) du module CV : import/révision, analyse de matching,
// offres comparées, recommandations + optimisation ATS.
export const CV_COPY = {
  fr: {
    import: {
      title: "Importer votre CV",
      text: "Téléchargez votre CV, vérifiez les informations extraites, puis collez l'offre cible pour lancer le matching.",
      steps: [
        { title: "Télécharger CV", text: "Extraction automatique" },
        { title: "Réviser le profil", text: "Infos modifiables" },
        { title: "Poste visé", text: "Description de l'offre" },
        { title: "Analyse", text: "Match & Optimisation" }
      ],
      stepEyebrow: "Étape {n} sur 4",
      dropTitle: "Glissez-déposez votre CV ici",
      dropRelease: "Relâchez pour importer votre CV",
      dropOr: "ou",
      dropBrowse: "parcourez vos fichiers",
      dropMaxSize: "7 Mo max.",
      uploadBadFormat: "Format non pris en charge : importez un PDF, DOCX, DOC ou TXT.",
      uploadTooLarge: "Fichier trop volumineux (7 Mo maximum). Exportez votre CV en PDF plus léger.",
      uploadEmpty: "Ce fichier est vide.",
      extractingSteps: ["Lecture du fichier", "Extraction des informations", "Structuration du profil"],
      lastCvLabel: "Dernier CV importé",
      lastCvContinue: "Continuer avec ce CV",
      extractTitle: "Ce que l'IA extrait",
      extractItems: [
        { icon: "profile", label: "Identité et coordonnées" },
        { icon: "edit", label: "Titre et résumé professionnel" },
        { icon: "briefcase", label: "Expériences et missions" },
        { icon: "history", label: "Formations et certifications" },
        { icon: "globe", label: "Compétences et langues" }
      ],
      privacyText: "Vous gardez la main : tout est modifiable à l'étape suivante, et vos CV peuvent être supprimés à tout moment depuis l'historique.",
      completenessTitle: "Profil complété",
      completenessMissing: "À compléter :",
      completenessFull: "Toutes les informations clés sont renseignées.",
      fieldFirstName: "Prénom",
      fieldLastName: "Nom",
      fieldPhone: "Téléphone",
      fieldLocation: "Localisation",
      fieldHeadline: "Titre",
      fieldSummary: "Résumé",
      fieldSkills: "Compétences",
      fieldExperiences: "Expériences",
      fieldEducation: "Formation",
      fieldLanguages: "Langues",
      countSkills: "compétences",
      countExperiences: "expériences",
      countEducation: "formations",
      countLanguages: "langues",
      reviewBarHint: "Vérifiez et complétez les informations extraites avant de continuer.",
      pasteOffer: "Coller",
      clearOffer: "Effacer",
      jobTipsTitle: "Pour une analyse précise",
      jobTips: [
        "Copiez l'annonce complète : missions, profil recherché et compétences.",
        "Depuis LinkedIn, Indeed, Welcome to the Jungle ou le site de l'entreprise.",
        "L'IA en extrait le poste, l'entreprise, le contrat, les compétences et les missions."
      ],
      offerDescription: "Description",
      offerMissions: "Missions principales",
      factExperience: "{years} an(s) d'expérience min.",
      uploadTitle: "Téléchargez votre CV",
      uploadText: "Nous extrayons les informations pour préparer votre profil candidat.",
      analysingTitle: "Analyse de votre CV...",
      analysingText: "Cela prend généralement 10-20 secondes.",
      reviewTitle: "Révision de l'extraction",
      reviewText: "Vérifiez et corrigez les informations avant de les enregistrer.",
      reimport: "Réimporter le CV",
      saveContinue: "Enregistrer & continuer",
      personalInfo: "Informations personnelles",
      summary: "Résumé professionnel",
      skillsLanguages: "Compétences & langues",
      experiences: "Expériences",
      educationBlock: "Formation",
      certifications: "Certifications",
      interests: "Centres d'intérêt",
      addSkill: "Ajouter compétence",
      addLanguage: "Ajouter langue",
      addExperience: "Ajouter expérience",
      addEducation: "Ajouter formation",
      addCertification: "Ajouter certification",
      addInterest: "Ajouter intérêt",
      jobTitle: "Poste visé",
      jobText: "Collez la description complète du poste ci-dessous.",
      jobDescription: "Description du poste",
      jobSummaryTitle: "Résumé du poste",
      jobSummaryText: "Vérifiez les détails extraits avant de lancer l'analyse.",
      technicalSkills: "Compétences techniques",
      softSkills: "Soft skills",
      noSkillsDetected: "Aucune détectée dans le texte collé",
      backToEdit: "Retour à l'édition",
      reviewJob: "Vérifier le poste",
      analyseJob: "Lancer l'analyse",
      reviewingJob: "Analyse de l'offre...",
      extractionReady: "Extraction prête à réviser.",
      chooseFile: "Choisir un fichier CV",
      fileDone: "CV détecté et analysé",
      formats: "Formats acceptés: txt, pdf, doc, docx",
      history: "Historique CV",
      emptyHistory: "Aucun CV enregistré.",
      offerTitle: "Coller l'offre cible",
      offerText: "Le matching se base sur cette offre et compare aussi des offres marketplace.",
      offerPlaceholder: "Collez l'offre d'emploi complète ici...",
      chars: "caractères",
      ready: "Prêt",
      minimum: "Minimum 50 caractères",
      analysing: "Analyse en cours...",
      analyse: "Analyser mon profil",
      matchingTitle: "Analyse du matching en cours...",
      matchingText: "L'IA compare votre profil à l'offre. Cela prend généralement 10-20 secondes.",
      matchScoreLabel: "Score de compatibilité",
      matchHeroEyebrow: "Résultat de l'analyse IA",
      matchTierText_excellent: "Votre profil correspond très bien à cette offre : c'est le moment de postuler, avec une lettre soignée.",
      matchTierText_good: "Votre profil correspond bien à l'offre. Quelques ajustements ciblés renforceront votre candidature.",
      matchTierText_average: "Votre profil couvre une partie des attentes. Travaillez les compétences à renforcer avant de postuler.",
      matchTierText_weak: "L'écart avec l'offre est important. Renforcez votre CV ou ciblez un poste plus proche de votre profil.",
      matchOptimizeCta: "Optimiser mon CV pour cette offre",
      matchCoverageLabel: "Compétences de l'offre",
      matchCoverageHint: "présentes dans votre CV",
      matchStrengthsCount: "points forts",
      matchToStrengthenCount: "à renforcer",
      matchNoStrengths: "Aucun point fort identifié pour cette offre.",
      matchSkillsTitle: "Compétences demandées",
      matchSkillsPresent: "Présentes dans votre CV",
      matchSkillsNonePresent: "Aucune compétence de l'offre n'apparaît encore dans votre CV.",
      matchToStrengthen: "À renforcer",
      matchToStrengthenHint: "Ajoutez-les à votre CV si vous les maîtrisez, sinon mettez en avant des compétences proches.",
      matchNextTitle: "Et maintenant ?",
      matchNextText: "Poursuivez votre candidature avec les modules IA, déjà préparés pour cette offre.",
      nextLetterTitle: "Rédiger la lettre",
      nextLetterText: "Une lettre de motivation personnalisée à partir de votre CV et de cette offre.",
      nextInterviewTitle: "S'entraîner à l'entretien",
      nextInterviewText: "Un recruteur IA vous pose les questions du poste, avec un bilan détaillé.",
      nextNegotiationTitle: "Préparer la négociation",
      nextNegotiationText: "Entraînez-vous à défendre votre salaire face à un recruteur IA.",
      matchNextGo: "Commencer",
      matchStrengths: "Points forts",
      matchMissingKeywords: "Mots-clés manquants",
      matchCulturalFit: "Adéquation avec le poste",
      matchRecommendations: "Recommandations stratégiques",
      matchNoMissingKeywords: "Aucun mot-clé majeur ne manque, bravo.",
      matchResultsTitle: "Résultats d'Analyse",
      matchResultsSubtitle: "Détail de votre score de match.",
      matchFeedbackQuestion: "Cette analyse vous a-t-elle été utile ?",
      matchFeedbackYes: "Oui",
      matchFeedbackNo: "Non",
      matchFeedbackThanks: "Merci pour votre retour !",
      matchNetworkingTitle: "Opportunités Réseautage",
      matchNetworkingText: "Connectez-vous avec des employés chez {company} pour augmenter vos chances.",
      matchNetworkingButton: "Trouver des contacts dans l'entreprise",
      matchNetworkingSearching: "Préparation des recherches...",
      matchNetworkingEmpty: "Career CV n'a pas accès à un annuaire LinkedIn : voici des recherches ciblées à lancer vous-même en un clic.",
      matchNetworkingOpenLinkedin: "Chercher sur LinkedIn",
      matchNetworkingRoleLabel: "Personnes au poste visé",
      matchNetworkingRecruiterLabel: "Recruteurs",
      matchNetworkingHrLabel: "Équipe RH",
      matchCvLanguageLabel: "Langue du CV",
      matchPreviewCv: "Prévisualiser CV",
      matchHidePreview: "Masquer l'aperçu",
      matchShare: "Partager",
      matchShareCopied: "Résumé copié dans le presse-papiers.",
      matchDownloadPdf: "Télécharger PDF",
      matchCvPreviewTitle: "Aperçu CV Optimisé",
      matchCvPreviewEmpty: "Importez et révisez votre CV pour voir un aperçu ici.",
      cvPreviewSummary: "Résumé professionnel",
      cvPreviewExperience: "Expérience",
      cvPreviewEducation: "Formation",
      cvPreviewTechnicalSkills: "Compétences techniques",
      cvPreviewSoftSkills: "Compétences comportementales",
      cvPreviewLanguages: "Langues",
      cvPreviewCertifications: "Certifications",
      cvPreviewInterests: "Centres d'intérêt",
      cvPreviewProjects: "Projets",
      cvPreviewSocial: "Réseaux sociaux",
      cvPreviewPortfolio: "Portfolio",
      cvTemplateClassic: "Classique",
      cvTemplateSidebar: "Colonne latérale"
    },

    analysis: {
      unavailableTitle: "Analyse indisponible",
      unavailableText: "Importez un CV et lancez le matching depuis l'onglet Importer.",
      skillCoverage: "Couverture compétences",
      experienceFit: "Adéquation expérience",
      verdict: "Verdict",
      domain: "Compatibilité par domaine",
      quickRead: "Lecture rapide",
      strengths: "Points forts",
      gaps: "Points à combler"
    },
    offers: {
      unavailableTitle: "Offres indisponibles",
      unavailableText: "Lance une analyse pour débloquer la comparaison des offres.",
      title: "Matching CV × Offres",
      average: "Score de compatibilité",
      premiumAccess: "Accès premium",
      open: "ouvert",
      closed: "fermé",
      skills: "compétences",
      locked: "Verrouillé",
      detected: "Compétences détectées",
      noDetection: "Aucune détection.",
      mainGaps: "Gaps principaux",
      noGap: "Aucun écart majeur"
    },
    cv: {
      unavailableTitle: "Recommandations indisponibles",
      unavailableText: "Lance une analyse pour générer les recommandations CV.",
      title: "Plan d'amélioration du CV",
      text: "Recommandations automatiques basées sur les écarts détectés pendant le matching.",
      atsScoreTitle: "Score ATS pour cette offre",
      atsMatched: "mots-clés du poste retrouvés dans votre CV",
      atsOptimizeTitle: "Optimiser mon CV pour cette offre",
      atsOptimizeText: "L'IA reformule votre accroche, votre résumé et vos expériences pour mieux matcher les mots-clés de l'offre, sans jamais inventer une compétence ou une expérience que vous n'avez pas.",
      atsOptimizeBtn: "Optimiser mon CV (1 jeton)",
      atsOptimizing: "Optimisation en cours…",
      atsResultTitle: "Résultat de l'optimisation",
      atsHeadline: "Accroche optimisée",
      atsSummary: "Résumé optimisé",
      atsExperiences: "Expériences reformulées",
      atsSkillsOrder: "Compétences réordonnées (mêmes compétences, priorité à celles de l'offre)",
      atsMissingKeywords: "Mots-clés demandés par l'offre mais absents de votre CV",
      atsMissingKeywordsHint: "Ajoutez-les vous-même uniquement si vous maîtrisez réellement ces compétences, elles ne sont jamais ajoutées automatiquement à votre CV.",
      atsNotesTitle: "Note de l'IA",
      atsApply: "Appliquer au CV",
      atsApplying: "Enregistrement…",
      atsApplied: "Optimisation appliquée et enregistrée sur votre CV. Vous pouvez le télécharger en PDF ci-dessous.",
      atsNoOffer: "Analysez d'abord une offre depuis Importer CV pour optimiser votre CV en fonction d'un poste précis."
    },
  },
  en: {
    import: {
      title: "Import your CV",
      text: "Upload your CV, review the extracted profile, then paste the target job to launch matching.",
      steps: [
        { title: "Upload CV", text: "Automatic extraction" },
        { title: "Review profile", text: "Editable data" },
        { title: "Target role", text: "Job description" },
        { title: "Analysis", text: "Match & Optimization" }
      ],
      stepEyebrow: "Step {n} of 4",
      dropTitle: "Drag and drop your CV here",
      dropRelease: "Release to import your CV",
      dropOr: "or",
      dropBrowse: "browse your files",
      dropMaxSize: "7 MB max.",
      uploadBadFormat: "Unsupported format: import a PDF, DOCX, DOC or TXT file.",
      uploadTooLarge: "File too large (7 MB maximum). Export a lighter PDF.",
      uploadEmpty: "This file is empty.",
      extractingSteps: ["Reading the file", "Extracting information", "Structuring the profile"],
      lastCvLabel: "Last imported CV",
      lastCvContinue: "Continue with this CV",
      extractTitle: "What the AI extracts",
      extractItems: [
        { icon: "profile", label: "Identity and contact details" },
        { icon: "edit", label: "Headline and summary" },
        { icon: "briefcase", label: "Experience and missions" },
        { icon: "history", label: "Education and certifications" },
        { icon: "globe", label: "Skills and languages" }
      ],
      privacyText: "You stay in control: everything is editable in the next step, and your CVs can be deleted at any time from the history.",
      completenessTitle: "Profile completed",
      completenessMissing: "To complete:",
      completenessFull: "All key information is filled in.",
      fieldFirstName: "First name",
      fieldLastName: "Last name",
      fieldPhone: "Phone",
      fieldLocation: "Location",
      fieldHeadline: "Headline",
      fieldSummary: "Summary",
      fieldSkills: "Skills",
      fieldExperiences: "Experience",
      fieldEducation: "Education",
      fieldLanguages: "Languages",
      countSkills: "skills",
      countExperiences: "experiences",
      countEducation: "degrees",
      countLanguages: "languages",
      reviewBarHint: "Check and complete the extracted information before continuing.",
      pasteOffer: "Paste",
      clearOffer: "Clear",
      jobTipsTitle: "For an accurate analysis",
      jobTips: [
        "Copy the full posting: missions, profile sought and skills.",
        "From LinkedIn, Indeed, Welcome to the Jungle or the company website.",
        "The AI extracts the role, company, contract, skills and missions."
      ],
      offerDescription: "Description",
      offerMissions: "Main missions",
      factExperience: "{years}+ year(s) of experience",
      uploadTitle: "Upload your CV",
      uploadText: "We extract the information needed to prepare your candidate profile.",
      analysingTitle: "Analyzing your CV...",
      analysingText: "This usually takes 10-20 seconds.",
      reviewTitle: "Extraction review",
      reviewText: "Check and correct the information before saving it.",
      reimport: "Reimport CV",
      saveContinue: "Save & continue",
      personalInfo: "Personal information",
      summary: "Professional summary",
      skillsLanguages: "Skills & languages",
      experiences: "Experience",
      educationBlock: "Education",
      certifications: "Certifications",
      interests: "Interests",
      addSkill: "Add skill",
      addLanguage: "Add language",
      addExperience: "Add experience",
      addEducation: "Add education",
      addCertification: "Add certification",
      addInterest: "Add interest",
      jobTitle: "Target role",
      jobText: "Paste the full job description below.",
      jobDescription: "Job description",
      jobSummaryTitle: "Job summary",
      jobSummaryText: "Review the extracted details before launching the analysis.",
      technicalSkills: "Technical skills",
      softSkills: "Soft skills",
      noSkillsDetected: "None detected in the pasted text",
      backToEdit: "Back to editing",
      reviewJob: "Review job",
      analyseJob: "Analyze job",
      reviewingJob: "Analyzing job...",
      extractionReady: "Extraction ready to review.",
      chooseFile: "Choose a CV file",
      fileDone: "CV detected and analyzed",
      formats: "Accepted formats: txt, pdf, doc, docx",
      history: "CV history",
      emptyHistory: "No CV saved.",
      offerTitle: "Paste the target job",
      offerText: "Matching uses this job post and also compares marketplace jobs.",
      offerPlaceholder: "Paste the full job description here...",
      chars: "characters",
      ready: "Ready",
      minimum: "Minimum 50 characters",
      analysing: "Analysis running...",
      analyse: "Analyze my profile",
      matchingTitle: "Running match analysis...",
      matchingText: "The AI compares your profile to the job. This usually takes 10-20 seconds.",
      matchScoreLabel: "Compatibility score",
      matchHeroEyebrow: "AI analysis result",
      matchTierText_excellent: "Your profile is a great fit for this job: time to apply, with a polished cover letter.",
      matchTierText_good: "Your profile fits the job well. A few targeted tweaks will strengthen your application.",
      matchTierText_average: "Your profile covers part of the expectations. Work on the skills to strengthen before applying.",
      matchTierText_weak: "The gap with the job is significant. Strengthen your CV or target a role closer to your profile.",
      matchOptimizeCta: "Optimise my CV for this job",
      matchCoverageLabel: "Job skills",
      matchCoverageHint: "found in your CV",
      matchStrengthsCount: "strengths",
      matchToStrengthenCount: "to strengthen",
      matchNoStrengths: "No strength identified for this job.",
      matchSkillsTitle: "Required skills",
      matchSkillsPresent: "Found in your CV",
      matchSkillsNonePresent: "None of the job skills appear in your CV yet.",
      matchToStrengthen: "To strengthen",
      matchToStrengthenHint: "Add them to your CV if you master them, otherwise highlight related skills.",
      matchNextTitle: "What's next?",
      matchNextText: "Continue your application with the AI modules, already set up for this job.",
      nextLetterTitle: "Write the cover letter",
      nextLetterText: "A personalised cover letter based on your CV and this job.",
      nextInterviewTitle: "Practise the interview",
      nextInterviewText: "An AI recruiter asks you the role's questions, with a detailed report.",
      nextNegotiationTitle: "Prepare the negotiation",
      nextNegotiationText: "Practise defending your salary against an AI recruiter.",
      matchNextGo: "Start",
      matchStrengths: "Strengths",
      matchMissingKeywords: "Missing keywords",
      matchCulturalFit: "Fit with the role",
      matchRecommendations: "Strategic recommendations",
      matchNoMissingKeywords: "No major keyword is missing, nice work.",
      matchResultsTitle: "Analysis Results",
      matchResultsSubtitle: "Detail of your match score.",
      matchFeedbackQuestion: "Was this analysis useful?",
      matchFeedbackYes: "Yes",
      matchFeedbackNo: "No",
      matchFeedbackThanks: "Thanks for your feedback!",
      matchNetworkingTitle: "Networking opportunities",
      matchNetworkingText: "Connect with people working at {company} to boost your chances.",
      matchNetworkingButton: "Find contacts at this company",
      matchNetworkingSearching: "Preparing searches...",
      matchNetworkingEmpty: "Career CV has no LinkedIn directory access: here are targeted searches you can run yourself in one click.",
      matchNetworkingOpenLinkedin: "Search on LinkedIn",
      matchNetworkingRoleLabel: "People in the target role",
      matchNetworkingRecruiterLabel: "Recruiters",
      matchNetworkingHrLabel: "HR team",
      matchCvLanguageLabel: "CV language",
      matchPreviewCv: "Preview CV",
      matchHidePreview: "Hide preview",
      matchShare: "Share",
      matchShareCopied: "Summary copied to clipboard.",
      matchDownloadPdf: "Download PDF",
      matchCvPreviewTitle: "Optimized CV Preview",
      matchCvPreviewEmpty: "Import and review your CV to see a preview here.",
      cvPreviewSummary: "Professional summary",
      cvPreviewExperience: "Experience",
      cvPreviewEducation: "Education",
      cvPreviewTechnicalSkills: "Technical skills",
      cvPreviewSoftSkills: "Soft skills",
      cvPreviewLanguages: "Languages",
      cvPreviewCertifications: "Certifications",
      cvPreviewInterests: "Interests",
      cvPreviewProjects: "Projects",
      cvPreviewSocial: "Social links",
      cvPreviewPortfolio: "Portfolio",
      cvTemplateClassic: "Classic",
      cvTemplateSidebar: "Sidebar"
    },

    analysis: {
      unavailableTitle: "Analysis unavailable",
      unavailableText: "Import a CV and run matching from the Import tab.",
      skillCoverage: "Skill coverage",
      experienceFit: "Experience fit",
      verdict: "Verdict",
      domain: "Compatibility by domain",
      quickRead: "Quick read",
      strengths: "Strengths",
      gaps: "Gaps to close"
    },
    offers: {
      unavailableTitle: "Jobs unavailable",
      unavailableText: "Run an analysis to unlock job comparison.",
      title: "CV × Jobs matching",
      average: "Compatibility score",
      premiumAccess: "Premium access",
      open: "open",
      closed: "closed",
      skills: "skills",
      locked: "Locked",
      detected: "Detected skills",
      noDetection: "No detection.",
      mainGaps: "Main gaps",
      noGap: "No major gap"
    },
    cv: {
      unavailableTitle: "Recommendations unavailable",
      unavailableText: "Run an analysis to generate CV recommendations.",
      title: "CV improvement plan",
      text: "Automatic recommendations based on gaps detected during matching.",
      atsScoreTitle: "ATS score for this job",
      atsMatched: "job keywords found in your CV",
      atsOptimizeTitle: "Optimize my CV for this job",
      atsOptimizeText: "The AI rewrites your headline, summary and experiences to better match the job's keywords, never inventing a skill or experience you don't have.",
      atsOptimizeBtn: "Optimize my CV (1 token)",
      atsOptimizing: "Optimizing…",
      atsResultTitle: "Optimization result",
      atsHeadline: "Optimized headline",
      atsSummary: "Optimized summary",
      atsExperiences: "Rewritten experiences",
      atsSkillsOrder: "Reordered skills (same skills, job-relevant ones first)",
      atsMissingKeywords: "Keywords the job asks for but that are missing from your CV",
      atsMissingKeywordsHint: "Only add these yourself if you genuinely have these skills, they're never added to your CV automatically.",
      atsNotesTitle: "AI note",
      atsApply: "Apply to my CV",
      atsApplying: "Saving…",
      atsApplied: "Optimization applied and saved to your CV. You can download it as a PDF below.",
      atsNoOffer: "First analyze a job offer from Import CV to optimize your CV for a specific role."
    },
  }
};
