// Textes (FR/EN) du module CV : import/révision, analyse de matching,
// offres comparées, recommandations + optimisation ATS.
export const CV_COPY = {
  fr: {
    import: {
      title: "Importer votre CV",
      text: "Téléchargez votre CV, vérifiez les informations extraites, puis collez l'offre cible pour lancer le matching.",
      steps: [
        { title: "Télécharger CV", text: "Extraction automatique" },
        { title: "Réviser le profil", text: "Infos modifiables" },
        { title: "Poste visé", text: "Description de l'offre" },
        { title: "Analyse", text: "Match & Optimisation" }
      ],
      uploadTitle: "Téléchargez votre CV",
      uploadText: "Nous extrayons les informations pour préparer votre profil candidat.",
      analysingTitle: "Analyse de votre CV...",
      analysingText: "Cela prend généralement 10-20 secondes.",
      reviewTitle: "Révision de l'extraction",
      reviewText: "Vérifiez et corrigez les informations avant de les enregistrer.",
      reimport: "Réimporter le CV",
      saveContinue: "Enregistrer & continuer",
      personalInfo: "Informations personnelles",
      summary: "Résumé professionnel",
      skillsLanguages: "Compétences & langues",
      experiences: "Expériences",
      educationBlock: "Formation",
      certifications: "Certifications",
      interests: "Centres d'intérêt",
      addSkill: "Ajouter compétence",
      addLanguage: "Ajouter langue",
      addExperience: "Ajouter expérience",
      addEducation: "Ajouter formation",
      addCertification: "Ajouter certification",
      addInterest: "Ajouter intérêt",
      jobTitle: "Poste visé",
      jobText: "Collez la description complète du poste ci-dessous.",
      jobDescription: "Description du poste",
      jobSummaryTitle: "Résumé du poste",
      jobSummaryText: "Vérifiez les détails extraits avant de lancer l'analyse.",
      technicalSkills: "Compétences techniques",
      softSkills: "Soft skills",
      noSkillsDetected: "Aucune détectée dans le texte collé",
      backToEdit: "Retour à l'édition",
      reviewJob: "Vérifier le poste",
      analyseJob: "Analyser le job",
      reviewingJob: "Analyse de l'offre...",
      extractionReady: "Extraction prête à réviser.",
      chooseFile: "Choisir un fichier CV",
      fileDone: "CV détecté et analysé",
      formats: "Formats acceptés: txt, pdf, doc, docx",
      history: "Historique CV",
      emptyHistory: "Aucun CV enregistré.",
      offerTitle: "Coller l'offre cible",
      offerText: "Le matching se base sur cette offre et compare aussi des offres marketplace.",
      offerPlaceholder: "Collez l'offre d'emploi complète ici...",
      chars: "caractères",
      ready: "Prêt",
      minimum: "Minimum 50 caractères",
      analysing: "Analyse en cours...",
      analyse: "Analyser mon profil",
      matchingTitle: "Analyse du matching en cours...",
      matchingText: "L'IA compare votre profil à l'offre. Cela prend généralement 10-20 secondes.",
      matchScoreLabel: "Score de compatibilité",
      matchStrengths: "Points forts",
      matchMissingKeywords: "Mots-clés manquants",
      matchCulturalFit: "Fit culturel",
      matchRecommendations: "Recommandations stratégiques",
      matchNoMissingKeywords: "Aucun mot-clé majeur ne manque, bravo.",
      matchResultsTitle: "Résultats d'Analyse",
      matchResultsSubtitle: "Détail de votre score de match.",
      matchFeedbackQuestion: "Cette analyse vous a-t-elle été utile ?",
      matchFeedbackYes: "Oui",
      matchFeedbackNo: "Non",
      matchFeedbackThanks: "Merci pour votre retour !",
      matchNetworkingTitle: "Opportunités Réseautage",
      matchNetworkingText: "Connectez-vous avec des employés chez {company} pour augmenter vos chances.",
      matchNetworkingButton: "Trouver des contacts dans l'entreprise",
      matchNetworkingSearching: "Préparation des recherches...",
      matchNetworkingEmpty: "Career CV n'a pas accès à un annuaire LinkedIn : voici des recherches ciblées à lancer vous-même en un clic.",
      matchNetworkingOpenLinkedin: "Chercher sur LinkedIn",
      matchNetworkingRoleLabel: "Personnes au poste visé",
      matchNetworkingRecruiterLabel: "Recruteurs",
      matchNetworkingHrLabel: "Équipe RH",
      matchCvLanguageLabel: "Langue du CV",
      matchPreviewCv: "Prévisualiser CV",
      matchHidePreview: "Masquer l'aperçu",
      matchShare: "Partager",
      matchShareCopied: "Résumé copié dans le presse-papiers.",
      matchDownloadPdf: "Télécharger PDF",
      matchDownloadPdfGenerating: "Génération du PDF...",
      matchCvOverflowNotice:
        "Ce CV est trop dense pour tenir sur 1 page malgré la mise en page resserrée : le PDF téléchargé fait plusieurs pages. Raccourcissez certaines descriptions pour revenir à 1 page.",
      matchCvPreviewTitle: "Aperçu CV Optimisé",
      matchCvPreviewEmpty: "Importez et révisez votre CV pour voir un aperçu ici.",
      cvPreviewSummary: "Résumé professionnel",
      cvPreviewExperience: "Expérience",
      cvPreviewEducation: "Formation",
      cvPreviewTechnicalSkills: "Compétences techniques",
      cvPreviewSoftSkills: "Compétences comportementales",
      cvPreviewLanguages: "Langues",
      cvPreviewCertifications: "Certifications",
      cvPreviewInterests: "Centres d'intérêt",
      cvPreviewProjects: "Projets",
      cvPreviewSocial: "Réseaux sociaux",
      cvPreviewPortfolio: "Portfolio",
      cvTemplateClassic: "Classique",
      cvTemplateSidebar: "Colonne latérale"
    },

    analysis: {
      unavailableTitle: "Analyse indisponible",
      unavailableText: "Importez un CV et lancez le matching depuis l'onglet Importer.",
      skillCoverage: "Couverture compétences",
      experienceFit: "Adéquation expérience",
      verdict: "Verdict",
      domain: "Compatibilité par domaine",
      quickRead: "Lecture rapide",
      strengths: "Points forts",
      gaps: "Points à combler"
    },
    offers: {
      unavailableTitle: "Offres indisponibles",
      unavailableText: "Lance une analyse pour débloquer la comparaison des offres.",
      title: "Matching CV × Offres",
      average: "Score moyen du portefeuille",
      premiumAccess: "Accès premium",
      open: "ouvert",
      closed: "fermé",
      skills: "compétences",
      locked: "Verrouillé",
      detected: "Compétences détectées",
      noDetection: "Aucune détection.",
      mainGaps: "Gaps principaux",
      noGap: "Aucun écart majeur"
    },
    cv: {
      unavailableTitle: "Recommandations indisponibles",
      unavailableText: "Lance une analyse pour générer les recommandations CV.",
      title: "Plan d'amélioration du CV",
      text: "Recommandations automatiques basées sur les écarts détectés pendant le matching.",
      atsScoreTitle: "Score ATS pour cette offre",
      atsMatched: "mots-clés du poste retrouvés dans votre CV",
      atsOptimizeTitle: "Optimiser mon CV pour cette offre",
      atsOptimizeText: "L'IA reformule votre accroche, votre résumé et vos expériences pour mieux matcher les mots-clés de l'offre — sans jamais inventer une compétence ou une expérience que vous n'avez pas.",
      atsOptimizeBtn: "Optimiser mon CV (1 jeton)",
      atsOptimizing: "Optimisation en cours…",
      atsResultTitle: "Résultat de l'optimisation",
      atsHeadline: "Accroche optimisée",
      atsSummary: "Résumé optimisé",
      atsExperiences: "Expériences reformulées",
      atsSkillsOrder: "Compétences réordonnées (mêmes compétences, priorité à celles de l'offre)",
      atsMissingKeywords: "Mots-clés demandés par l'offre mais absents de votre CV",
      atsMissingKeywordsHint: "Ajoutez-les vous-même uniquement si vous maîtrisez réellement ces compétences — elles ne sont jamais ajoutées automatiquement à votre CV.",
      atsNotesTitle: "Note de l'IA",
      atsApply: "Appliquer au CV",
      atsApplying: "Enregistrement…",
      atsApplied: "Optimisation appliquée et enregistrée sur votre CV. Vous pouvez le télécharger en PDF ci-dessous.",
      atsNoOffer: "Analysez d'abord une offre depuis Importer CV pour optimiser votre CV en fonction d'un poste précis."
    },
  },
  en: {
    import: {
      title: "Import your CV",
      text: "Upload your CV, review the extracted profile, then paste the target job to launch matching.",
      steps: [
        { title: "Upload CV", text: "Automatic extraction" },
        { title: "Review profile", text: "Editable data" },
        { title: "Target role", text: "Job description" },
        { title: "Analysis", text: "Match & Optimization" }
      ],
      uploadTitle: "Upload your CV",
      uploadText: "We extract the information needed to prepare your candidate profile.",
      analysingTitle: "Analyzing your CV...",
      analysingText: "This usually takes 10-20 seconds.",
      reviewTitle: "Extraction review",
      reviewText: "Check and correct the information before saving it.",
      reimport: "Reimport CV",
      saveContinue: "Save & continue",
      personalInfo: "Personal information",
      summary: "Professional summary",
      skillsLanguages: "Skills & languages",
      experiences: "Experience",
      educationBlock: "Education",
      certifications: "Certifications",
      interests: "Interests",
      addSkill: "Add skill",
      addLanguage: "Add language",
      addExperience: "Add experience",
      addEducation: "Add education",
      addCertification: "Add certification",
      addInterest: "Add interest",
      jobTitle: "Target role",
      jobText: "Paste the full job description below.",
      jobDescription: "Job description",
      jobSummaryTitle: "Job summary",
      jobSummaryText: "Review the extracted details before launching the analysis.",
      technicalSkills: "Technical skills",
      softSkills: "Soft skills",
      noSkillsDetected: "None detected in the pasted text",
      backToEdit: "Back to editing",
      reviewJob: "Review job",
      analyseJob: "Analyze job",
      reviewingJob: "Analyzing job...",
      extractionReady: "Extraction ready to review.",
      chooseFile: "Choose a CV file",
      fileDone: "CV detected and analyzed",
      formats: "Accepted formats: txt, pdf, doc, docx",
      history: "CV history",
      emptyHistory: "No CV saved.",
      offerTitle: "Paste the target job",
      offerText: "Matching uses this job post and also compares marketplace jobs.",
      offerPlaceholder: "Paste the full job description here...",
      chars: "characters",
      ready: "Ready",
      minimum: "Minimum 50 characters",
      analysing: "Analysis running...",
      analyse: "Analyze my profile",
      matchingTitle: "Running match analysis...",
      matchingText: "The AI compares your profile to the job. This usually takes 10-20 seconds.",
      matchScoreLabel: "Compatibility score",
      matchStrengths: "Strengths",
      matchMissingKeywords: "Missing keywords",
      matchCulturalFit: "Cultural fit",
      matchRecommendations: "Strategic recommendations",
      matchNoMissingKeywords: "No major keyword is missing, nice work.",
      matchResultsTitle: "Analysis Results",
      matchResultsSubtitle: "Detail of your match score.",
      matchFeedbackQuestion: "Was this analysis useful?",
      matchFeedbackYes: "Yes",
      matchFeedbackNo: "No",
      matchFeedbackThanks: "Thanks for your feedback!",
      matchNetworkingTitle: "Networking opportunities",
      matchNetworkingText: "Connect with people working at {company} to boost your chances.",
      matchNetworkingButton: "Find contacts at this company",
      matchNetworkingSearching: "Preparing searches...",
      matchNetworkingEmpty: "Career CV has no LinkedIn directory access: here are targeted searches you can run yourself in one click.",
      matchNetworkingOpenLinkedin: "Search on LinkedIn",
      matchNetworkingRoleLabel: "People in the target role",
      matchNetworkingRecruiterLabel: "Recruiters",
      matchNetworkingHrLabel: "HR team",
      matchCvLanguageLabel: "CV language",
      matchPreviewCv: "Preview CV",
      matchHidePreview: "Hide preview",
      matchShare: "Share",
      matchShareCopied: "Summary copied to clipboard.",
      matchDownloadPdf: "Download PDF",
      matchDownloadPdfGenerating: "Generating PDF...",
      matchCvOverflowNotice:
        "This CV is too dense to fit on 1 page even with the tightened layout: the downloaded PDF spans multiple pages. Shorten some descriptions to get back to 1 page.",
      matchCvPreviewTitle: "Optimized CV Preview",
      matchCvPreviewEmpty: "Import and review your CV to see a preview here.",
      cvPreviewSummary: "Professional summary",
      cvPreviewExperience: "Experience",
      cvPreviewEducation: "Education",
      cvPreviewTechnicalSkills: "Technical skills",
      cvPreviewSoftSkills: "Soft skills",
      cvPreviewLanguages: "Languages",
      cvPreviewCertifications: "Certifications",
      cvPreviewInterests: "Interests",
      cvPreviewProjects: "Projects",
      cvPreviewSocial: "Social links",
      cvPreviewPortfolio: "Portfolio",
      cvTemplateClassic: "Classic",
      cvTemplateSidebar: "Sidebar"
    },

    analysis: {
      unavailableTitle: "Analysis unavailable",
      unavailableText: "Import a CV and run matching from the Import tab.",
      skillCoverage: "Skill coverage",
      experienceFit: "Experience fit",
      verdict: "Verdict",
      domain: "Compatibility by domain",
      quickRead: "Quick read",
      strengths: "Strengths",
      gaps: "Gaps to close"
    },
    offers: {
      unavailableTitle: "Jobs unavailable",
      unavailableText: "Run an analysis to unlock job comparison.",
      title: "CV × Jobs matching",
      average: "Average portfolio score",
      premiumAccess: "Premium access",
      open: "open",
      closed: "closed",
      skills: "skills",
      locked: "Locked",
      detected: "Detected skills",
      noDetection: "No detection.",
      mainGaps: "Main gaps",
      noGap: "No major gap"
    },
    cv: {
      unavailableTitle: "Recommendations unavailable",
      unavailableText: "Run an analysis to generate CV recommendations.",
      title: "CV improvement plan",
      text: "Automatic recommendations based on gaps detected during matching.",
      atsScoreTitle: "ATS score for this job",
      atsMatched: "job keywords found in your CV",
      atsOptimizeTitle: "Optimize my CV for this job",
      atsOptimizeText: "The AI rewrites your headline, summary and experiences to better match the job's keywords — never inventing a skill or experience you don't have.",
      atsOptimizeBtn: "Optimize my CV (1 token)",
      atsOptimizing: "Optimizing…",
      atsResultTitle: "Optimization result",
      atsHeadline: "Optimized headline",
      atsSummary: "Optimized summary",
      atsExperiences: "Rewritten experiences",
      atsSkillsOrder: "Reordered skills (same skills, job-relevant ones first)",
      atsMissingKeywords: "Keywords the job asks for but that are missing from your CV",
      atsMissingKeywordsHint: "Only add these yourself if you genuinely have these skills — they're never added to your CV automatically.",
      atsNotesTitle: "AI note",
      atsApply: "Apply to my CV",
      atsApplying: "Saving…",
      atsApplied: "Optimization applied and saved to your CV. You can download it as a PDF below.",
      atsNoOffer: "First analyze a job offer from Import CV to optimize your CV for a specific role."
    },
  }
};
