export const COVER_LETTER_COPY = {
  fr: {
    title: "Lettre & Email IA",
    subtitle: "Une lettre et un email de candidature uniques, écrits à partir de votre vrai profil et de l'offre visée.",
    toneLabel: "Choisissez un ton",
    toneFormal: "Formel",
    toneEnthusiastic: "Enthousiaste",
    toneDirect: "Direct",
    templateLabel: "Choisissez un modèle",
    colorLabel: "Choisissez une couleur",
    generate: "Générer la lettre et l'email (2 jetons)",
    generateUnlimited: "Générer la lettre et l'email",
    regenerate: "Régénérer la lettre (1 jeton)",
    regenerateUnlimited: "Régénérer la lettre",
    noTokens: "Vous n'avez plus de jetons.",
    noTokensCta: "Passer à un plan supérieur",
    edit: "Modifier",
    cancelEdit: "Annuler",
    saveEdit: "Enregistrer",
    copy: "Copier",
    copied: "Copié !",
    download: "Télécharger en PDF",
    empty: "Importez un CV et analysez une offre pour débloquer ce module.",
    noTokens: "Il vous manque des jetons pour générer votre lettre et votre email. Passez à un plan supérieur.",
    generating: "Rédaction en cours...",
    history: "Lettres",
    newConversation: "Nouvelle lettre & email",
    resumeHint: "Reprenez une lettre déjà générée.",
    noHistory: "Aucune lettre pour l'instant.",
    deleteConversation: "Supprimer",
    deleteConfirm: "Supprimer cette lettre ?",
    cancel: "Annuler",
    untitled: "Lettre sans titre",
    historyBadgeLetter: "Lettre",
    historyBadgeEmail: "Email",
    letterSectionTitle: "Lettre de motivation",
    emailSectionTitle: "Email de candidature",
    recipientNameLabel: "Nom du destinataire",
    recipientNamePlaceholder: "ex : Jean Dupont",
    recipientEmailLabel: "Email du destinataire",
    recipientEmailPlaceholder: "ex : jean.dupont@entreprise.com",
    emailTypeLabel: "Type d'email",
    emailType_offer_reply: "Réponse à une offre",
    emailType_spontaneous: "Candidature spontanée",
    emailType_follow_up: "Relance",
    emailLengthLabel: "Longueur",
    emailLength_short: "Courte",
    emailLength_long: "Longue",
    generateEmail: "Générer l'email (1 jeton)",
    generateEmailUnlimited: "Générer l'email",
    regenerateEmail: "Régénérer l'email (1 jeton)",
    regenerateEmailUnlimited: "Régénérer l'email",
    generatingEmail: "Rédaction en cours...",
    emailSubjectLabel: "Objet",
    copySubject: "Copier l'objet",
    copyBody: "Copier le corps",
    copyBoth: "Copier tout"
  },
  en: {
    title: "Letter & Email AI",
    subtitle: "A unique letter and application email, written from your real profile and the targeted job.",
    toneLabel: "Choose a tone",
    toneFormal: "Formal",
    toneEnthusiastic: "Enthusiastic",
    toneDirect: "Direct",
    templateLabel: "Choose a template",
    colorLabel: "Choose a color",
    generate: "Generate letter & email (2 tokens)",
    generateUnlimited: "Generate letter & email",
    regenerate: "Regenerate letter (1 token)",
    regenerateUnlimited: "Regenerate letter",
    noTokens: "You're out of tokens.",
    noTokensCta: "Upgrade your plan",
    edit: "Edit",
    cancelEdit: "Cancel",
    saveEdit: "Save",
    copy: "Copy",
    copied: "Copied!",
    download: "Download as PDF",
    empty: "Import a CV and analyze a job offer to unlock this module.",
    noTokens: "You don't have enough tokens to generate your letter and email. Upgrade your plan.",
    generating: "Writing in progress...",
    history: "Letters",
    newConversation: "New letter & email",
    resumeHint: "Resume a letter you already generated.",
    noHistory: "No letter yet.",
    deleteConversation: "Delete",
    deleteConfirm: "Delete this letter?",
    cancel: "Cancel",
    untitled: "Untitled letter",
    historyBadgeLetter: "Letter",
    historyBadgeEmail: "Email",
    letterSectionTitle: "Cover letter",
    emailSectionTitle: "Application email",
    recipientNameLabel: "Recipient name",
    recipientNamePlaceholder: "e.g. John Smith",
    recipientEmailLabel: "Recipient email",
    recipientEmailPlaceholder: "e.g. john.smith@company.com",
    emailTypeLabel: "Email type",
    emailType_offer_reply: "Reply to a job posting",
    emailType_spontaneous: "Unsolicited application",
    emailType_follow_up: "Follow-up",
    emailLengthLabel: "Length",
    emailLength_short: "Short",
    emailLength_long: "Long",
    generateEmail: "Generate email (1 token)",
    generateEmailUnlimited: "Generate email",
    regenerateEmail: "Regenerate email (1 token)",
    regenerateEmailUnlimited: "Regenerate email",
    generatingEmail: "Writing in progress...",
    emailSubjectLabel: "Subject",
    copySubject: "Copy subject",
    copyBody: "Copy body",
    copyBoth: "Copy all"
  }
};
