export const COVER_LETTER_COPY = {
  fr: {
    title: "Lettre de motivation IA",
    eyebrow: "Module IA · Lettre",
    unlockCta: "Importer un CV et analyser une offre",
    tokenChip: "{count} jeton(s) disponible(s)",
    unlimitedChip: "Générations illimitées",
    toneHint: "Le style d'écriture de votre lettre.",
    toneFormalDesc: "Sobre et professionnel, pour les grands comptes et le secteur public.",
    toneEnthusiasticDesc: "Met en avant votre motivation, idéal pour les start-up.",
    toneDirectDesc: "Court et factuel : vos résultats d'abord.",
    templateHint: "La mise en page du document exporté en PDF.",
    generateTitle: "Générez votre lettre",
    generateText: "L'IA croise votre CV et l'offre ciblée pour rédiger une lettre personnalisée, modifiable avant l'export.",
    tipsTitle: "Conseils",
    targetResumedTitle: "Poste de cette lettre",
    targetResumedNote: "Offre enregistrée avec la lettre ouverte. « Nouvelle lettre » repart de votre dernière offre analysée.",
    tips: [
      "Relisez et ajoutez une anecdote personnelle avant l'envoi.",
      "Citez un projet ou un chiffre de l'entreprise visée.",
      "Une page maximum : les recruteurs lisent en diagonale."
    ],
    subtitle: "Une lettre unique, écrite à partir de votre vrai profil et de l'offre visée.",
    toneLabel: "Choisissez un ton",
    toneFormal: "Formel",
    toneEnthusiastic: "Enthousiaste",
    toneDirect: "Direct",
    templateLabel: "Choisissez un modèle",
    generate: "Générer (1 jeton)",
    generateUnlimited: "Générer",
    regenerate: "Régénérer (1 jeton)",
    regenerateUnlimited: "Régénérer",
    noTokens: "Vous n'avez plus de jetons.",
    noTokensCta: "Passer à un plan supérieur",
    edit: "Modifier",
    cancelEdit: "Annuler",
    saveEdit: "Enregistrer",
    copy: "Copier",
    copied: "Copié !",
    download: "Télécharger en PDF",
    empty: "Importez un CV et analysez une offre pour débloquer ce module.",
    noTokens: "Vous n'avez plus de jetons. Passez à un plan supérieur pour générer votre lettre.",
    generating: "Rédaction en cours...",
    history: "Lettres",
    newConversation: "Nouvelle lettre",
    resumeHint: "Reprenez une lettre déjà générée.",
    noHistory: "Aucune lettre pour l'instant.",
    deleteConversation: "Supprimer",
    deleteConfirm: "Supprimer cette lettre ?",
    cancel: "Annuler",
    untitled: "Lettre sans titre"
  },
  en: {
    title: "AI Cover Letter",
    eyebrow: "AI module · Letter",
    unlockCta: "Import a CV and analyze a job offer",
    tokenChip: "{count} token(s) available",
    unlimitedChip: "Unlimited generations",
    toneHint: "The writing style of your letter.",
    toneFormalDesc: "Sober and professional, for large companies and the public sector.",
    toneEnthusiasticDesc: "Highlights your motivation, ideal for start-ups.",
    toneDirectDesc: "Short and factual: your results first.",
    templateHint: "The layout of the exported PDF document.",
    generateTitle: "Generate your letter",
    generateText: "The AI matches your CV with the targeted job to write a personalised letter you can edit before exporting.",
    tipsTitle: "Tips",
    targetResumedTitle: "Role for this letter",
    targetResumedNote: "Job saved with the open letter. \"New letter\" starts again from your latest analyzed job.",
    tips: [
      "Proofread and add a personal story before sending.",
      "Mention a project or figure from the company.",
      "One page maximum: recruiters skim."
    ],
    subtitle: "A unique letter written from your real profile and the targeted job.",
    toneLabel: "Choose a tone",
    toneFormal: "Formal",
    toneEnthusiastic: "Enthusiastic",
    toneDirect: "Direct",
    templateLabel: "Choose a template",
    generate: "Generate (1 token)",
    generateUnlimited: "Generate",
    regenerate: "Regenerate (1 token)",
    regenerateUnlimited: "Regenerate",
    noTokens: "You're out of tokens.",
    noTokensCta: "Upgrade your plan",
    edit: "Edit",
    cancelEdit: "Cancel",
    saveEdit: "Save",
    copy: "Copy",
    copied: "Copied!",
    download: "Download as PDF",
    empty: "Import a CV and analyze a job offer to unlock this module.",
    noTokens: "You're out of tokens. Upgrade your plan to generate your letter.",
    generating: "Writing in progress...",
    history: "Letters",
    newConversation: "New letter",
    resumeHint: "Resume a letter you already generated.",
    noHistory: "No letter yet.",
    deleteConversation: "Delete",
    deleteConfirm: "Delete this letter?",
    cancel: "Cancel",
    untitled: "Untitled letter"
  }
};
