export const COVER_LETTER_COPY = {
  fr: {
    title: "Lettre de motivation IA",
    subtitle: "Une lettre unique, écrite à partir de votre vrai profil et de l'offre visée.",
    toneLabel: "Choisissez un ton",
    toneFormal: "Formel",
    toneEnthusiastic: "Enthousiaste",
    toneDirect: "Direct",
    templateLabel: "Choisissez un modèle",
    generate: "Générer (1 jeton)",
    regenerate: "Régénérer (1 jeton)",
    edit: "Modifier",
    cancelEdit: "Annuler",
    saveEdit: "Enregistrer",
    copy: "Copier",
    copied: "Copié !",
    download: "Télécharger en PDF",
    empty: "Importez un CV et analysez une offre pour débloquer ce module.",
    noTokens: "Vous n'avez plus de jetons. Passez à un plan supérieur pour générer votre lettre.",
    generating: "Rédaction en cours...",
    history: "Lettres",
    newConversation: "Nouvelle lettre",
    resumeHint: "Reprenez une lettre déjà générée.",
    noHistory: "Aucune lettre pour l'instant.",
    deleteConversation: "Supprimer",
    deleteConfirm: "Supprimer cette lettre ?",
    cancel: "Annuler",
    untitled: "Lettre sans titre"
  },
  en: {
    title: "AI Cover Letter",
    subtitle: "A unique letter written from your real profile and the targeted job.",
    toneLabel: "Choose a tone",
    toneFormal: "Formal",
    toneEnthusiastic: "Enthusiastic",
    toneDirect: "Direct",
    templateLabel: "Choose a template",
    generate: "Generate (1 token)",
    regenerate: "Regenerate (1 token)",
    edit: "Edit",
    cancelEdit: "Cancel",
    saveEdit: "Save",
    copy: "Copy",
    copied: "Copied!",
    download: "Download as PDF",
    empty: "Import a CV and analyze a job offer to unlock this module.",
    noTokens: "You're out of tokens. Upgrade your plan to generate your letter.",
    generating: "Writing in progress...",
    history: "Letters",
    newConversation: "New letter",
    resumeHint: "Resume a letter you already generated.",
    noHistory: "No letter yet.",
    deleteConversation: "Delete",
    deleteConfirm: "Delete this letter?",
    cancel: "Cancel",
    untitled: "Untitled letter"
  }
};
