// Textes (FR/EN) du module Négociation salariale.
export const NEGOTIATION_COPY = {
  fr: {
    title: "Simulateur de négociation salariale",
    eyebrow: "Module IA · Négociation",
    unlockCta: "Importer un CV et analyser une offre",
    tokenChip: "{count} jeton(s) disponible(s)",
    unlimitedChip: "Sessions illimitées",
    prepareTitle: "Préparez la session",
    prepareText: "Indiquez votre objectif : le recruteur IA négociera à partir de l'offre ciblée et de votre profil.",
    targetHint: "Laissez vide pour que le recruteur ouvre la discussion sans connaître votre objectif.",
    howTitle: "Comment ça se passe",
    howSteps: [
      { title: "Le recruteur ouvre la discussion", text: "Il joue le rôle d'un vrai recruteur de l'entreprise visée, avec ses objections." },
      { title: "Vous argumentez", text: "Un conseil de coaching s'affiche après chaque réponse pour ajuster votre stratégie." },
      { title: "Vous recevez votre bilan", text: "Points forts et axes d'amélioration, à relire avant l'entretien réel." }
    ],
    tipsTitle: "Conseils",
    tips: [
      "Annoncez une fourchette plutôt qu'un montant unique.",
      "Appuyez-vous sur la fourchette de marché affichée.",
      "Négociez aussi le reste : télétravail, primes, formation."
    ],
    reportReady: "Bilan disponible",
    exchanges: "{count} échange(s)",
    notStarted: "Non commencée",
    targetResumedTitle: "Poste de cette négociation",
    targetResumedNote: "Offre enregistrée avec la négociation ouverte. « Nouvelle négociation » repart de votre dernière offre analysée.",
    recruiterName: "Recruteur IA",
    targetShort: "Objectif :",
    subtitle: "Entraînez-vous face à un recruteur IA réaliste avant l'entretien décisif.",
    targetLabel: "Prétention salariale visée (optionnel)",
    targetPlaceholder: "Ex : 42 000",
    start: "Démarrer la négociation (1 jeton)",
    startUnlimited: "Démarrer la négociation",
    noTokens: "Vous n'avez plus de jetons.",
    noTokensCta: "Passer à un plan supérieur",
    starting: "Connexion au recruteur...",
    placeholder: "Votre réponse au recruteur...",
    send: "Envoyer",
    tip: "Conseil coaching",
    finish: "Terminer & voir mon bilan",
    finishing: "Analyse de la négociation...",
    summary: "Bilan de négociation",
    strengths: "Points forts",
    improvements: "Axes d'amélioration",
    empty: "Importez un CV et analysez une offre pour débloquer ce module.",
    noTokens: "Vous n'avez plus de jetons. Passez à un plan supérieur pour démarrer une négociation.",
    history: "Conversations",
    newConversation: "Nouvelle négociation",
    resumeHint: "Reprenez une négociation déjà commencée.",
    noHistory: "Aucune conversation pour l'instant.",
    deleteConversation: "Supprimer",
    deleteConfirm: "Supprimer cette conversation ?",
    cancel: "Annuler",
    untitled: "Négociation sans titre"
  },
  en: {
    title: "Salary Negotiation Simulator",
    eyebrow: "AI module · Negotiation",
    unlockCta: "Import a CV and analyze a job offer",
    tokenChip: "{count} token(s) available",
    unlimitedChip: "Unlimited sessions",
    prepareTitle: "Prepare the session",
    prepareText: "Set your goal: the AI recruiter negotiates based on the targeted job and your profile.",
    targetHint: "Leave empty to let the recruiter open without knowing your goal.",
    howTitle: "How it works",
    howSteps: [
      { title: "The recruiter opens", text: "They play a real recruiter from the targeted company, objections included." },
      { title: "You make your case", text: "A coaching tip appears after each answer to adjust your strategy." },
      { title: "You get your report", text: "Strengths and areas to improve, to review before the real interview." }
    ],
    tipsTitle: "Tips",
    tips: [
      "Give a range rather than a single figure.",
      "Lean on the market range shown.",
      "Negotiate the rest too: remote work, bonuses, training."
    ],
    reportReady: "Report ready",
    exchanges: "{count} exchange(s)",
    notStarted: "Not started",
    targetResumedTitle: "Role for this negotiation",
    targetResumedNote: "Job saved with the open negotiation. \"New negotiation\" starts again from your latest analyzed job.",
    recruiterName: "AI recruiter",
    targetShort: "Goal:",
    subtitle: "Train against a realistic AI recruiter before the real conversation.",
    targetLabel: "Target salary (optional)",
    targetPlaceholder: "E.g. 55,000",
    start: "Start negotiation (1 token)",
    startUnlimited: "Start negotiation",
    noTokens: "You're out of tokens.",
    noTokensCta: "Upgrade your plan",
    starting: "Connecting to recruiter...",
    placeholder: "Your reply to the recruiter...",
    send: "Send",
    tip: "Coaching tip",
    finish: "Finish & see my report",
    finishing: "Analyzing the negotiation...",
    summary: "Negotiation report",
    strengths: "Strengths",
    improvements: "Areas to improve",
    empty: "Import a CV and analyze a job offer to unlock this module.",
    noTokens: "You're out of tokens. Upgrade your plan to start a negotiation.",
    history: "Conversations",
    newConversation: "New negotiation",
    resumeHint: "Resume a negotiation you already started.",
    noHistory: "No conversation yet.",
    deleteConversation: "Delete",
    deleteConfirm: "Delete this conversation?",
    cancel: "Cancel",
    untitled: "Untitled negotiation"
  }
};
