// Textes (FR/EN) du module Négociation salariale.
export const NEGOTIATION_COPY = {
  fr: {
    title: "Simulateur de négociation salariale",
    subtitle: "Entraînez-vous face à un recruteur IA réaliste avant l'entretien décisif.",
    targetLabel: "Prétention salariale visée (optionnel)",
    targetPlaceholder: "Ex : 42 000",
    start: "Démarrer la négociation (1 jeton)",
    starting: "Connexion au recruteur...",
    placeholder: "Votre réponse au recruteur...",
    send: "Envoyer",
    tip: "Conseil coaching",
    finish: "Terminer & voir mon bilan",
    finishing: "Analyse de la négociation...",
    summary: "Bilan de négociation",
    strengths: "Points forts",
    improvements: "Axes d'amélioration",
    empty: "Importe un CV et analyse une offre pour débloquer ce module.",
    noTokens: "Vous n'avez plus de jetons. Passez à un plan supérieur pour démarrer une négociation.",
    history: "Conversations",
    newConversation: "Nouvelle négociation",
    resumeHint: "Reprends une négociation déjà commencée.",
    noHistory: "Aucune conversation pour l'instant.",
    deleteConversation: "Supprimer",
    deleteConfirm: "Supprimer cette conversation ?",
    untitled: "Négociation sans titre"
  },
  en: {
    title: "Salary Negotiation Simulator",
    subtitle: "Train against a realistic AI recruiter before the real conversation.",
    targetLabel: "Target salary (optional)",
    targetPlaceholder: "E.g. 55,000",
    start: "Start negotiation (1 token)",
    starting: "Connecting to recruiter...",
    placeholder: "Your reply to the recruiter...",
    send: "Send",
    tip: "Coaching tip",
    finish: "Finish & see my report",
    finishing: "Analyzing the negotiation...",
    summary: "Negotiation report",
    strengths: "Strengths",
    improvements: "Areas to improve",
    empty: "Import a CV and analyze a job offer to unlock this module.",
    noTokens: "You're out of tokens. Upgrade your plan to start a negotiation.",
    history: "Conversations",
    newConversation: "New negotiation",
    resumeHint: "Resume a negotiation you already started.",
    noHistory: "No conversation yet.",
    deleteConversation: "Delete",
    deleteConfirm: "Delete this conversation?",
    untitled: "Untitled negotiation"
  }
};
